FROM gcr.io/deeplearning-platform-release/xgboost-cpu.1-1

RUN conda install nodejs  
RUN apt-get install -y npm
RUN pip install jupyterlab-nvdashboard && jupyter labextension install jupyterlab-nvdashboard

ADD run.sh /workspace/workshop
ENTRYPOINT ["bash", "run.sh"]

jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
10:26
