FROM gcr.io/deeplearning-platform-release/xgboost-cpu.1-1

RUN pip install jupyterlab-nvdashboard &&\
          jupyter labextension install jupyterlab-nvdashboard

EXPOSE 8080

ADD run.sh /workspace/workshop
ENTRYPOINT ["bash", "run.sh"]

